apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
 name: cerouno
 region: us-east-1

vpc:
  cidr: "192.168.0.0/16"
  clusterEndpoints:
    publicAccess: true
    privateAccess: false

managedNodeGroups:
- name: ondemand
  instanceType: t3.medium
  minSize: 1
  desiredCapacity: 1
  maxSize: 1
  ssh:
    allow: true
    enableSsm: true
  availabilityZones: ["us-east-1a", "us-east-1b"]
  privateNetworking: false
  iam:
    withAddonPolicies:
      autoScaler: true
      ebs: true
      fsx: true
      efs: true
      albIngress: true
      cloudWatch: true
      imageBuilder: true

- name: spot
  instanceTypes: ["t3.medium", "t3.large", "t1.large", "t3a.large", "m5.large"]
  iam:
    withAddonPolicies:
      autoScaler: true
      ebs: true
      fsx: true
      efs: true
      albIngress: true
      cloudWatch: true
      imageBuilder: true
  ssh:
    allow: true
    enableSsm: true
  spot: true
  minSize: 2
  desiredCapacity: 2
  maxSize: 2
  availabilityZones: ["us-east-1a", "us-east-1b"]
  privateNetworking: false

availabilityZones: ["us-east-1a", "us-east-1b"]
