apiVersion: v1
kind: Pod
metadata:
  name: my-pod-req
spec:
  containers:
  - name: myapp
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
    resources:
      requests:
        memory: 64Mi
        cpu: 10000m
