apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod
spec:
  containers:
  - name: myapp-container
    image: nginx
    startupProbe:
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 1
      exec:
        command:
        - cat
        - /etc/nginx/nginx.conf
    livenessProbe:
      initialDelaySeconds: 60
      periodSeconds: 5
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 1
      tcpSocket:
        host:
        port: 80
