apiVersion: v1
kind: Pod
metadata:
  name: readiness-pod
spec:
  containers:
  - name: myapp-container
    image: nginx
    startupProbe:
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 1
      exec:
        command:
        - cat
        - /etc/nginx/nginx.conf
    livenessProbe:
      initialDelaySeconds: 2
      periodSeconds: 5
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 1
      tcpSocket:
        host:
        port: 80
      readinessProbe:
        initialDelaySeconds: 2
        periodSeconds: 5
        timeoutSeconds: 1
        successThreshold: 5
        failureThreshold: 5
        httpGet:
          host:
          scheme: HTTP
          path: /
          port: 81
