apiVersion: v1
kind: Pod
metadata:
  name: deployment-viewer-pod
  namespace: sa-rbac
spec:
  serviceAccountName: shared-sa
  containers:
  - name: busybox
    image: radial/busyboxplus:curl
    command: ['sh', '-c', 'TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token); while true; do if curl -s -o /dev/null -k -m 3 -H "Authorization: Bearer $TOKEN" https://kubernetes.default.svc.cluster.local/api/v1/namespaces/sa-rbac/deployments/; then echo "[SUCCESS] Successfully viewed Deployments!"; else exit 1; fi; sleep 5; done']
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-viewer-pod
  namespace: sa-permissions-test
spec:
  serviceAccountName: shared-sa
  containers:
  - name: busybox
    image: radial/busyboxplus:curl
    command: ['sh', '-c', 'TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token); while true; do if curl -s -o /dev/null -k -m 3 -H "Authorization: Bearer $TOKEN" https://kubernetes.default.svc.cluster.local/api/v1/namespaces/sa-rbac/pods/; then echo "[SUCCESS] Successfully viewed Pods!"; else exit 1; fi; sleep 5; done']
