apiVersion: v1
kind: Namespace
metadata:
  name: sa-rbac

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: shared-sa
  namespace: sa-rbac
automountServiceAccountToken: true

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sa-role
  namespace: sa-rbac
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-rb
  namespace: sa-rbac
subjects:
- kind: ServiceAccount
  name: shared-sa
  namespace: sa-rbac
roleRef:
  kind: Role
  name: shared-sa-role
  apiGroup: rbac.authorization.k8s.io
