apiVersion: v1
kind: Namespace
metadata:
  name: sa-rbac

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: shared-sa
  namespace: sa-rbac
automountServiceAccountToken: true

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sa-role
  namespace: sa-rbac
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-rb
  namespace: sa-rbac
subjects:
- kind: ServiceAccount
  name: shared-sa
  namespace: sa-rbac
roleRef:
  kind: Role
  name: sa-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Pod
metadata:
  name: deployment-viewer-pod
  namespace: sa-rbac
spec:
  serviceAccountName: shared-sa
  containers:
  - name: busybox
    image: radial/busyboxplus:curl
    command: ['sh', '-c', 'sleep 3600;']
    volumeMounts:
    - name: scripts-volume
      mountPath: /root/scripts
  volumes:
  - name: scripts-volume
    configMap:
      name: scripts-cm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-cm
  namespace: sa-rbac
data:
  deployment.sh: |
    #! /bin/bash
    TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
    curl -s -k -m 3 -H "Authorization: Bearer $TOKEN" https://kubernetes.default.svc.cluster.local/api/v1/namespaces/sa-rbac/deployments/
  pod.sh: |
    #! /bin/bash
    TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
    curl -s -k -m 3 -H "Authorization: Bearer $TOKEN" https://kubernetes.default.svc.cluster.local/api/v1/namespaces/sa-rbac/pods/
