apiVersion: v1
kind: Pod
metadata:
  name: sc-failed-demo
spec:
  securityContext:
    runAsUser: 2001
    fsGroup: 3001
  containers:
  - name: sc-failed-demo
    image: diegoazd/security-context-demo
    command: ['sh', '-c', 'while true; do date >> /etc/message/message.txt && sleep 5 ; done;']
  restartPolicy: Always
